name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: npm
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Build
        run: |
          tsc

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish